### ISSUE TITLE
refusal to execute inline-script

### ISSUE THREAD

**Issue by gtarsia** [dino-dna/denolandia#4]
hey there, I browsed https://denolandia.cdaringe.com, and saw this problem in the console.
```
Refused to execute inline script because it violates
the following Content Security Policy directive: "script-src 'self'".

Either the 'unsafe-inline' keyword, a hash 
('sha256-1xxiJKv6VDywL35FZhTROWe1ONocWj7o9fVyBy3IAGg='),
or a nonce ('nonce-...') is required to enable inline execution.
```
I'm also getting no results.

I could try to post a pull request to fix this if you want.

**Comment by cdaringe** [comment]
Uh oh!  Well, that script error I speculate is immaterial to the lack of results, but a patch would certainly be welcome!  Given that the project isn't super interested in pursuing this further, I'm uncertain on how much maintenance to put into it.  If you have time to identify the data issue, I will absolutely accept it.  Probably something straight forward.  The system is easily runnable locally
